name: Update copyright year

on:
  schedule:
    - cron: '0 9 2 1 *'

  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: check out repository
        uses: actions/checkout@v4
        with:
          path: repo
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/build_tools
          token: ${{ secrets.READ_PAT }}
          path: tools
          ref: feature/copyright-year
          sparse-checkout: |
            scripts/copyright-year-bump

      - uses: ./tools/scripts/copyright-year-bump
        with:
          repo-path: repo
